name: BountySeekers
version: 1.0
description: This plugin allows players to place, raise, and claim bounties on other players' heads, with an item-reward based system.
author: MrKelpy
main: com.mrkelpy.bountyseekers.BountySeekers

commands:

  bounty:
    usage: /bounty <command>
    description: Master command. When used alone, displays the list of commands.

  bounty list:
    usage: /bounty list
    description: Displays the list of active bounties.

  bounty raise:
    usage: /bounty raise <player>
    description: Raises the bounty for a player by contributing to the player's bounty reward.
    permission: bounty.raise

  bounty silentraise:
    usage: /bounty silentraise <player>
    description: Raises the bounty for a player, hiding the identity of the benefactor.
    permission: bounty.silent.raise

  bounty reset:
    usage: /bounty reset <player>
    description: Resets the bounty for a player.
    permission: bounty.reset
