name: BountySeekers
version: 1.3.2
description: This plugin allows players to place, raise, and claim bounties on other players' heads, with an item-reward based system.
author: MrKelpy
main: com.mrkelpy.bountyseekers.v1_13.BountySeekers
api-version: 1.13

commands:

  bounty:
    usage: /bounty <command>
    description: Master command.

  bounty help:
    usage: /bounty help
    description: Displays the help menu.
    permission: bounty.help

  bounty list:
    usage: /bounty list
    description: Displays the list of active bounties.
    permission: bounty.list
  
  bounty check:
    usage: /bounty check <player>
    description: Directly displays the bounty on a player's head.
    permission: bounty.check

  bounty raise:
    usage: /bounty raise <player>
    description: Raises the bounty for a player by contributing to the player's bounty reward.
    permission: bounty.raise

  bounty silentraise:
    usage: /bounty silentraise <player>
    description: Raises the bounty for a player, hiding the identity of the benefactor.
    permission: bounty.silent.raise

  bounty reset:
    usage: /bounty reset <player>
    description: Resets the bounty for a player.
    permission: bounty.reset

  bounty setrewardlimit:
    usage: /bounty setrewardlimit <amount>
    description: Sets the maximum amount of rewards a player can receive for their bounty.
    permission: bounty.admin.setrewardlimit
    
  bounty setrewardfilters:
    usage: /bounty setrewardfilters
    description: Sets the filters for the rewards a player can receive for their bounty through a GUI.
    permission: bounty.admin.setrewardfilters
